baseURL = "https://yeongcheon.github.io/"
languageCode = "ko-ko"
title = "YeongCheon Tech Blog"
theme = "m10c"
pygmentsCodeFences=true
googleAnalytics = "UA-135478508-1"

[params]
  author = "YeongCheon Kim"
  description = "잡탕 웹개발자, 이맥스를 좋아해요"
  [[params.social]]
    name = "github"
    url = "https://github.com/yeongcheon"