baseURL = "https://yeongcheon.github.io/"
title = "꿀테크 블로그"
theme = ["whiteplain-dark"]
pygmentsCodeFences=true
pygmentsOptions = "linenos=table"
languageCode = "ko-ko"
# Disqus shortname
disqusShortname = "yeongcheonkim"
# google analytics tracking id
googleAnalytics = "UA-135478508-1"
# googleAnalytics = "Toracking ID"

# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright 2019 YeongCheon"

[params]
  description = "게을러지고 싶으면 공부해야 합니다."
  images = ["images/profile.png"]
  title = "꿀 빨고 싶으면 공부하자"
  categories = ["web"]
  # whether to use CDN or local file for fontawesome
  #useCDN = false
  # whether to include external sharing scripts and icons for twitter, facebook and co.
  #showShareIcons = false
  # Date format
  #dateFormat = "January 2, 2006"

# This is displayer in About page.
[params.author]
  name = "YeongCheon Kim"
  # Gravatar or Abatar image
  # gravatar = "Gravatar email or MD5 Hash"
  avatar = "images/profile.png"

  # twitter = "Twitter username"
  facebook = "yeongcheon.kim.3"
  # googleplus = "Googleplus username"
  # instagram = "Instagram username"
  # tumblr = "Tumblr username"
  # flickr = "Flickr username"
  # reddit = "Reddit username"
  # linkedin = "Linkedinu ysername"
  # slideshare = "Slideshare username"
  github = "yeongcheon"
  gitlab = "kyc1682"
  # bitbucket = "Bitbucket username"
  # stackoverflow = "Stackoverflow username"
  # jsfiddle = "Jsfiddle username"
  # codepen = "Codepen username"
  # deviantart = "Deviantart username"
  # behance = "Behance username"
  # dribbble = "Dribbble username"
  # wordpress = "Wordpress username"
  # medium = "Medium username"
  # foursquare = "Foursquare username"
  # xing = "Xing username"
  # quora = "Quora username"
  # youtube = "Youtube username"
  # vimeo = "Vimeo username"
  # whatsapp = "Whatsapp username"
  # skype = "Skype username"
  # snapchat = "Snapchat username"
  # pinterest = "Pinterest username"
  # telegram = "Telegram username"
  # vine = "Vine username"
  email = "kyc1682@gmail.com"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# Header Menu
# [[menu.main]]
#   name = "Categories"
#   identifier = "categories"
#   url = "/categories/"
#   weight = 1
[[menu.main]]
  name = "Tags"
  identifier = "tags"
  url = "/tags/"
  weight = 2
[[menu.main]]
  name = "Archives"
  identifier = "archives"
  url = "/posts/"
  weight = 3
[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
  weight = 4

# Footer Menu
[[menu.footer]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/about/"