#+HUGO_BASE_DIR: ../../
#+HUGO_SECTION: ./posts
#+HUGO_DRAFT: false

#+HUGO_WEIGHT: auto
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_TAGS: tinode golang chat "instant messaging"

#+TITLE: tinode series.002 - Install & Run
#+LAYOUT: post
#+AUTHOR: yeongcheon
#+DATE: "2019-05-28 00:00:00 +0900"

* 서론
  소스코드를 살펴보기에 앞서서 일단 프로그램 실행을 시켜보자. 이 글에서 설명하는 예제는 커밋 아이디 기준 [[https://github.com/YeongCheon/chat/commit/2558db90a50c80c974c2fccfec6b87ea44e4758b][2558db90a50c80c974c2fccfec6b87ea44e4758b]]을 바탕으로 설명한다. 사실 이 글을 안봐도 [[https://github.com/tinode/chat/blob/master/INSTALL.md][여기]]를 따라하면 보통을 무난하게 설치 및 실행을 할 수 있다. 이 가이드는 공식 가이드 중 [[https://github.com/tinode/chat/blob/master/INSTALL.md#building-from-source][Building from Source]], Mysql을 기준으로 설명한다.

* 실행환경 및 선행조건

  * Ubuntu 18.04 LTS

  * Golang이 설치되어 있어야 한다(기준 버전 : =1.12.5=).

  * Mysql이 설치되어 있어야 한다(기준 버전: =5.7=)

* 설치 및 실행하기

** source 파일 내려받기 및 바이너리 파일 install
다음 명령어를 입력한다.

#+BEGIN_SRC shell
go get -tags mysql github.com/tinode/chat/server && go install -tags mysql github.com/tinode/chat/server
go get -tags mysql github.com/tinode/chat/tinode-db && go install -tags mysql github.com/tinode/chat/tinode-db
#+END_SRC

첫번째 줄의 명령어는 실제로 동작하게 될 채팅서버와 연관된 소스코드를 다운로드 후 해당 소스코드를 컴파일하여 =$GOPATH/bin/= 경로에 =server= 라는 파일을 생성하는 명령어다.

두번째 줄의 명령어는 데이터베이스 셋팅을 위한 소스코드를 다운로드 후 해당 소스코드를 컴파일하여 위와 마찬가지로 =$GOPATH/bin/= 경로에 =tinode-db= 라는 파일을 생성하는 명령어다.

위의 명령어에서 눈여겨 볼 점은 =go get= 명령어와 =go install= 명령어 실행 시 모두 =-tags= 라는 옵션에 mysql이라는 값을 주었다는 점이다. =-tags= 옵션에 대한 자세한 설명은 [[https://golang.org/cmd/go/][공식문서]] 또는 [[https://jacking75.github.io/go_build/][블로그 글]]을 참고해보자.

** 데이터베이스 스키마 생성하기

MySQL에 데이터베이스 및 테이블을 생성하는 법을 알아보자.
우선 =$GOPATH/src/github.com/tinode/chat/tinode-db/tinode.conf= 파일을 열어서 db 접속정보가 올바른지 확인하자. 만약 접속정보와 다르다면(+당연히 대부분 다를거다+) 자신의 db 설정과 동일하게 고쳐주자. 다른부분은 건드릴 필요 없고 =store_config.adapters.mysql.dsn= 필드만 수정해주면 된다. 설정이 완료됐다면 아래의 명령어를 실행해주자.

#+BEGIN_SRC shell
$GOPATH/bin/tinode-db -config=$GOPATH/src/github.com/tinode/chat/tinode-db/tinode.conf
#+END_SRC

이때 터미널의 위치는 가급적이면 =$GOPATH/src/github.com/tinode/chat= 로 이동시킨 후 실행시키자. conf 파일 중 상대경로 옵션이 적용되어 있는 경우가 있어서 다른 위치에서 명령어를 실행 시 에러를 발생시키기도 한다. 그리고 혹시 테스트용 더미 데이터를 추가하고 싶은 경우엔 위의 명령어 뒤에 = -data=$GOPATH/src/github.com/tinode/chat/tinode-db/data.json= 를 붙여주자. 당연히 필수는 아니다.

명령어가 정상적으로 실행되었다면 터미널 창에 *All done.* 이라는 메세지가 뜬다.

** 채팅서버 실행시키기

이제 마지막으로 실제 동작할 채팅서버를 실행시켜보자. 채팅서버를 실행하기에 앞서 우선 폴더 몇개를 복사해서 이동시켜야 한다.

  * =$GOPATH/src/tinode/chat/server/templ= 폴더를 복사해서 =$GOPATH/bin/= 아래에 붙여넣는다. 이 폴더에는 사용자에게 발송할 메일, sms 등의 템플릿이 담겨있다. 이 템플릿은 고 언어의 기본 패키지인 [[https://golang.org/pkg/html/template/][http/template]] 패키지의 룰을 따른다.
  * =$GOPATH/src/tinode/chat/server/uploads= 폴더를 복사해서 =$GOPATH/bin/= 아래에 붙여넣는다(+이건 사실 빈 폴더라서 굳이 복붙까진 필요없다.+).

그리고 위에서 얘기한대로 터미널의 위치를 =$GOPATH/src/github.com/tinode/chat= 로 이동시킨 후 아래의 명령어를 실행해보자.

#+BEGIN_SRC shell
$GOPATH/bin/server -config=$GOPATH/src/github.com/tinode/chat/server/tinode.conf
#+END_SRC

실행 후 터미널에 *Listening for client HTTP connections on [:6060]* 메세지가 뜬다면 성공이다.
