# from: https://velog.io/@ceres/Github-Action%EC%9C%BC%EB%A1%9C-hugo%EB%B8%94%EB%A1%9C%EA%B7%B8-%EC%9E%90%EB%8F%99-%EB%B0%B0%ED%8F%AC%ED%95%98%EA%B8%B0
name: blog deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
    - name: Build Hugo Site
      run: hugo --minify
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.HUGO_BLOG_DEPLOY }}
        external_repository: YeongCheon/yeongcheon.github.io
        publish_branch: master
        publish_dir: ./public
