name: deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.74.2'
    - name: remove submodule cache
      run: git rm --cached public -f
    - name: Deploy yeongcheon.github.io
      run: ./deploy.sh
      
